/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaDatos.EntradaProducto;
import CapaNegocio.ColorearColumnasJTable;
import CapaNegocio.EntradaProductoBD;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Est.Invitado_04
 */
public class ModificarPreciosProductos_IU extends javax.swing.JInternalFrame {

    DefaultTableModel tabla_temporal;
    int filaSeleccionada;

    /**
     * Creates new form ModificarPreciosProductos_IU
     */
    public ModificarPreciosProductos_IU() {
        initComponents();
         ColorearColumnasJTable co15=new ColorearColumnasJTable(4, Color.YELLOW);
        
        tabla_reporte_producto.getColumnModel().getColumn(4).setCellRenderer(co15);
    }

    private void limpiar() {
        txtId.setText("");
        txtSerie.setText("");
        txtProducto.setText("");
        txtLote.setText("");
        txtFechaVcto.setText("");
        txtPresentacion.setText("");
        txtEquivalencia.setText("");
        txtStockEquivalencia.setText("");
        txtStockPresentacion.setText("");
        txtPrecioCompraPresentacion.setText("");
        txtPrecioCompraEquivalencia.setText("");
        txtMargenEquivalencia.setText("");
        txtMargenPresentacion.setText("");
        txtPrecioVentaPresentacion.setText("");
        txtPrecioVentaEquivalencia.setText("");

    }

    private void exito(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "MENSAJE", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }

    private void error(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ERROR", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
    }

    private void advertencia(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ADVERTENCIA", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
    }

    private void limpiar_tabla_formulario() {
        DefaultTableModel tabla_temporal_productos_temporal = (DefaultTableModel) tabla_reporte_producto.getModel();
        tabla_temporal_productos_temporal.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_reporte_producto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLote = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFechaVcto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPresentacion = new javax.swing.JTextField();
        txtEquivalencia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtStockPresentacion = new javax.swing.JTextField();
        txtStockEquivalencia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPrecioCompraPresentacion = new javax.swing.JTextField();
        txtPrecioCompraEquivalencia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMargenPresentacion = new javax.swing.JTextField();
        txtMargenEquivalencia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPrecioVentaPresentacion = new javax.swing.JTextField();
        txtPrecioVentaEquivalencia = new javax.swing.JTextField();
        txtCerrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("MODIFICAR PRECIOS PRODUCTOS");

        jLabel1.setText("PRODUCTO");

        txtBuscarProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarProductoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuscarProductoFocusLost(evt);
            }
        });
        txtBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarProductoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProductoKeyReleased(evt);
            }
        });

        tabla_reporte_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERIE", "PRODUCTO", "LOTE", "FECHAVCTO", "TIENDA"
            }
        ));
        tabla_reporte_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_reporte_productoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_reporte_producto);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producto a Modificar Precios", 0, 0, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel2.setText("ID");

        txtId.setEnabled(false);

        jLabel3.setText("SERIE");

        txtSerie.setEnabled(false);

        txtProducto.setEnabled(false);

        jLabel4.setText("PRODUCTO");

        txtLote.setEnabled(false);

        jLabel5.setText("LOTE");

        jLabel6.setText("FECHACVTO");

        txtFechaVcto.setEnabled(false);

        jLabel7.setText("MEDIDA");

        jLabel8.setText("PRESENTACION");

        txtPresentacion.setEnabled(false);

        txtEquivalencia.setEnabled(false);

        jLabel9.setText("EQUIVALENCIA");

        txtStockPresentacion.setEnabled(false);

        txtStockEquivalencia.setEnabled(false);

        jLabel10.setText("STOCK");

        txtPrecioCompraPresentacion.setEnabled(false);

        txtPrecioCompraEquivalencia.setEnabled(false);

        jLabel11.setText("PRECIO COMPRA");

        txtMargenPresentacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMargenPresentacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMargenPresentacionFocusLost(evt);
            }
        });
        txtMargenPresentacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMargenPresentacionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMargenPresentacionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMargenPresentacionKeyTyped(evt);
            }
        });

        txtMargenEquivalencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMargenEquivalenciaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMargenEquivalenciaFocusLost(evt);
            }
        });
        txtMargenEquivalencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMargenEquivalenciaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMargenEquivalenciaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMargenEquivalenciaKeyTyped(evt);
            }
        });

        jLabel12.setText("MARGEN");

        jLabel13.setText("PRECIO VENTA");

        txtPrecioVentaPresentacion.setEnabled(false);

        txtPrecioVentaEquivalencia.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaVcto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtStockEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addComponent(txtStockPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtPrecioCompraEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)
                            .addComponent(txtPrecioCompraPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtMargenEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtMargenPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtPrecioVentaEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)
                            .addComponent(txtPrecioVentaPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtFechaVcto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStockPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStockEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioCompraPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioCompraEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMargenPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMargenEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioVentaPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioVentaEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        txtCerrar.setText("CERRAR");
        txtCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        txtCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txtCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCerrarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lapiz.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModificarMousePressed(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarProducto))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_txtCerrarActionPerformed

    private void btnModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMousePressed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try {
            int aviso = JOptionPane.showConfirmDialog(rootPane, "Estas a punto de modificar los precios de ventas de " + txtProducto.getText());
            if (aviso == 0) {
                int margenPresentacion = Integer.parseInt(txtMargenPresentacion.getText());
                int margenEquivalencia = Integer.parseInt(txtMargenEquivalencia.getText());
                double precioVentaPresentacion = Double.parseDouble(txtPrecioVentaPresentacion.getText());
                double precioVentaEquivalencia = Double.parseDouble(txtPrecioVentaEquivalencia.getText());
                int idEntradaProducto = Integer.parseInt(txtId.getText());
                if (txtMargenPresentacion.getText().length() > 0) {
                    if (txtMargenEquivalencia.getText().length() > 0) {
                        EntradaProducto oEntradaProducto = new EntradaProducto();
                        EntradaProductoBD oEntradaProductoBD = new EntradaProductoBD();
                        oEntradaProducto.setMargenGananciaPresentacion(margenPresentacion);
                        oEntradaProducto.setMargenGananciaEquivalencia(margenEquivalencia);
                        oEntradaProducto.setPrecioVentaPresentacionMayor(precioVentaPresentacion);
                        oEntradaProducto.setPrecioVentaEquivalenciaMayor(precioVentaEquivalencia);
                        oEntradaProducto.setIdep(idEntradaProducto);
                        boolean rpta = oEntradaProductoBD.modificarPrecioProducto(oEntradaProducto);
                        if (rpta) {
                            exito("Se modifico los precios de ventas con exito !");
                            limpiar();
                            txtProducto.requestFocus();
                        } else {
                            error("Tienes problemas al modificar los precios");
                        }
                    } else {
                        advertencia("No debe estar vacio");
                        txtMargenEquivalencia.requestFocus();
                    }
                } else {
                    advertencia("No debe estar vacio");
                    txtMargenPresentacion.requestFocus();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }


    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtBuscarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductoKeyPressed
        // TODO add your handling code here:
        limpiar_tabla_formulario();
        
        String producto = txtBuscarProducto.getText();
        
        if (txtBuscarProducto.getText().length() > 2) {
            DefaultTableModel tabla_temporal_producto = (DefaultTableModel) tabla_reporte_producto.getModel();
            EntradaProductoBD oEntradaProductoBD = new EntradaProductoBD();
            
            tabla_temporal = oEntradaProductoBD.buscarProductoXdescripcion(producto);
            
            int cantidad = tabla_temporal.getRowCount();
            for (int i = 0; i < cantidad; i++) {

                String id = tabla_temporal.getValueAt(i, 0).toString();
                String serie = tabla_temporal.getValueAt(i, 3).toString();
                String descripcion = tabla_temporal.getValueAt(i, 4).toString();
                String lote = tabla_temporal.getValueAt(i, 2).toString();
                String fechaVcto = tabla_temporal.getValueAt(i, 11).toString();
                String tienda = tabla_temporal.getValueAt(i, 23).toString();
                
                Object[] data = {id, serie, descripcion, lote, fechaVcto, tienda};
                tabla_temporal_producto.addRow(data);

            }
        }
    }//GEN-LAST:event_txtBuscarProductoKeyPressed

    private void tabla_reporte_productoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_reporte_productoMousePressed
        // TODO add your handling code here:

        filaSeleccionada = tabla_reporte_producto.getSelectedRow();
        txtId.setText("" + tabla_reporte_producto.getValueAt(filaSeleccionada, 0));
        txtLote.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 2));
        txtSerie.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 3));
        txtProducto.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 4));
        txtFechaVcto.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 11));
        txtPresentacion.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 9));
        txtEquivalencia.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 10));
        txtStockPresentacion.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 12));
        txtStockEquivalencia.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 13));
        txtPrecioCompraPresentacion.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 14));
        txtPrecioCompraEquivalencia.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 15));
        txtPrecioVentaPresentacion.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 18));
        txtPrecioVentaEquivalencia.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 20));

        String presentacion = txtPresentacion.getText();
        String equivalencia = txtEquivalencia.getText();

        if (presentacion.equals(equivalencia)) {
            txtMargenPresentacion.setEnabled(false);
            txtMargenPresentacion.setText("0");
            txtMargenEquivalencia.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 17));

        } else {
            txtMargenPresentacion.setEnabled(true);
            txtMargenPresentacion.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 16));
            txtMargenEquivalencia.setText("" + tabla_temporal.getValueAt(filaSeleccionada, 17));

        }
    }//GEN-LAST:event_tabla_reporte_productoMousePressed

    private void txtBuscarProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarProductoKeyReleased

    private void txtMargenPresentacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMargenPresentacionKeyReleased
        // TODO add your handling code here:
        try {
            DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.ENGLISH);
            DecimalFormat df = new DecimalFormat("#.#", symbols);
            double precioCompraPresentacion = Double.parseDouble(txtPrecioCompraPresentacion.getText().trim());
            double margen = Integer.parseInt(txtMargenPresentacion.getText().trim());

            double gananciaPresentacion = precioCompraPresentacion * (margen / 100);

            double precioVentEquivalencia = precioCompraPresentacion + gananciaPresentacion;
            double redondeadoEquivalencia = Math.round(precioVentEquivalencia);
            txtPrecioVentaPresentacion.setText("" + df.format(redondeadoEquivalencia));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtMargenPresentacionKeyReleased

    private void txtMargenEquivalenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMargenEquivalenciaKeyReleased
        // TODO add your handling code here:
       try {
            DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.ENGLISH);
            DecimalFormat df = new DecimalFormat("#.#", symbols);
            double precioCompraEquivalencia = Double.parseDouble(txtPrecioCompraEquivalencia.getText().trim());
            double margen = Integer.parseInt(txtMargenEquivalencia.getText().trim());

            double gananciaEquivalencia = precioCompraEquivalencia * (margen / 100);

            double precioVentEquivalencia = precioCompraEquivalencia + gananciaEquivalencia;
            String redondeadoEquivalencia = df.format(precioVentEquivalencia);
            txtPrecioVentaEquivalencia.setText(redondeadoEquivalencia);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtMargenEquivalenciaKeyReleased

    private void txtBuscarProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarProductoFocusGained
        // TODO add your handling code here:
        
        txtBuscarProducto.setBackground(Color.yellow);
    }//GEN-LAST:event_txtBuscarProductoFocusGained

    private void txtBuscarProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarProductoFocusLost
        // TODO add your handling code here:
        
        txtBuscarProducto.setBackground(Color.white);
    }//GEN-LAST:event_txtBuscarProductoFocusLost

    private void txtMargenPresentacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMargenPresentacionFocusGained
        // TODO add your handling code here:
        txtMargenPresentacion.setBackground(Color.yellow);
    }//GEN-LAST:event_txtMargenPresentacionFocusGained

    private void txtMargenPresentacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMargenPresentacionFocusLost
        // TODO add your handling code here:
        txtMargenPresentacion.setBackground(Color.white);
    }//GEN-LAST:event_txtMargenPresentacionFocusLost

    private void txtMargenEquivalenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMargenEquivalenciaFocusGained
        // TODO add your handling code here:
        txtMargenEquivalencia.setBackground(Color.yellow);
    }//GEN-LAST:event_txtMargenEquivalenciaFocusGained

    private void txtMargenEquivalenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMargenEquivalenciaFocusLost
        // TODO add your handling code here:
        txtMargenEquivalencia.setBackground(Color.white);
    }//GEN-LAST:event_txtMargenEquivalenciaFocusLost

    private void txtMargenPresentacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMargenPresentacionKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtMargenEquivalencia.requestFocus();
        }
    }//GEN-LAST:event_txtMargenPresentacionKeyPressed

    private void txtMargenEquivalenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMargenEquivalenciaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnModificar.requestFocus();
            btnModificar.doClick();
        }
    }//GEN-LAST:event_txtMargenEquivalenciaKeyPressed

    private void txtMargenPresentacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMargenPresentacionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) ) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMargenPresentacionKeyTyped

    private void txtMargenEquivalenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMargenEquivalenciaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) ) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMargenEquivalenciaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabla_reporte_producto;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JButton txtCerrar;
    private javax.swing.JTextField txtEquivalencia;
    private javax.swing.JTextField txtFechaVcto;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtMargenEquivalencia;
    private javax.swing.JTextField txtMargenPresentacion;
    private javax.swing.JTextField txtPrecioCompraEquivalencia;
    private javax.swing.JTextField txtPrecioCompraPresentacion;
    private javax.swing.JTextField txtPrecioVentaEquivalencia;
    private javax.swing.JTextField txtPrecioVentaPresentacion;
    private javax.swing.JTextField txtPresentacion;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtStockEquivalencia;
    private javax.swing.JTextField txtStockPresentacion;
    // End of variables declaration//GEN-END:variables
}
