/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import CapaConexion.Conexion;
import CapaNegocio.AjustarColumnasJTable;
import CapaNegocio.ColorearColumnasJTable;
import CapaNegocio.DetalleCompraBD;
import CapaNegocio.DetalleVentaBD;
import CapaNegocio.VentaBD;
import static CapaPresentacion.Venta_IU.tabla_ventas;
import java.awt.Color;
import java.io.InputStream;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Est.Invitado_04
 */
public class ReporteVentasVarios_IU extends javax.swing.JInternalFrame {

    DefaultTableModel tabla_temporal_ventas, tabla_temporal_detalle_ventas;
    DefaultTableModel tabla_temporal;
    SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");

    public ReporteVentasVarios_IU() {
        initComponents();
        
    }

    private void limpiar_tabla_formulario() {
        tabla_temporal_ventas = (DefaultTableModel) tabla_reporte_ventas.getModel();
        tabla_temporal_ventas.setRowCount(0);
    }

    private void exito(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "MENSAJE", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }

    private void error(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ERROR", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
    }

    private void advertencia(String mensaje) {
        JOptionPane.showConfirmDialog(this, mensaje, "ADVERTENCIA", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
    }

    private double dineroRecaudado() {
        tabla_temporal_ventas = (DefaultTableModel) tabla_reporte_ventas.getModel();
        int maxPedidos = tabla_temporal_ventas.getRowCount();
        double total = 0;
        for (int i = 0; i < maxPedidos; i++) {
            total = total + Double.parseDouble(tabla_temporal_ventas.getValueAt(i, 4).toString());

        }
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_reporte_ventas = new javax.swing.JTable();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBuscarventasAnuladas = new javax.swing.JButton();
        btnImprimirVentasAnuladas = new javax.swing.JButton();
        dcFechaInicioVentasAnuladas = new com.toedter.calendar.JDateChooser();
        dcFechaFinalVentasAnuladas = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbDocumento = new javax.swing.JComboBox<>();
        btnBuscarVentasDocumentos = new javax.swing.JButton();
        btnImprimirVentasDocumentos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDineroRecaudadoDocumento = new javax.swing.JTextField();
        dcFechaInicioVentasDocumento = new com.toedter.calendar.JDateChooser();
        dcFechaFinalVentasDocumento = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBuscarVentasContado = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtDineroRecadadoVentasContado = new javax.swing.JTextField();
        btnIMprimirVentasContado = new javax.swing.JButton();
        dcFechaInicioVentasContado = new com.toedter.calendar.JDateChooser();
        dcFechaFinalVentasContado = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_reporte_detalle_ventas = new javax.swing.JTable();
        txtCerrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tabla_reporte_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDVENTA", "CLIENTE", "DOCUMENTO", "CORRELATIVO", "TOTAL", "FECHA", "ESTADO"
            }
        ));
        tabla_reporte_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_reporte_ventasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_reporte_ventas);
        if (tabla_reporte_ventas.getColumnModel().getColumnCount() > 0) {
            tabla_reporte_ventas.getColumnModel().getColumn(1).setPreferredWidth(400);
        }

        jTabbedPane5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("FECHA INICIO");

        jLabel3.setText("FECHA FINAL");

        btnBuscarventasAnuladas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/drive_magnify_1.png"))); // NOI18N
        btnBuscarventasAnuladas.setText("BUSCAR");
        btnBuscarventasAnuladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarventasAnuladasActionPerformed(evt);
            }
        });

        btnImprimirVentasAnuladas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/impresora1.png"))); // NOI18N
        btnImprimirVentasAnuladas.setText("IMPRIMIR");
        btnImprimirVentasAnuladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirVentasAnuladasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dcFechaInicioVentasAnuladas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcFechaFinalVentasAnuladas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnBuscarventasAnuladas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(btnImprimirVentasAnuladas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(442, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcFechaFinalVentasAnuladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcFechaInicioVentasAnuladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscarventasAnuladas)
                        .addComponent(btnImprimirVentasAnuladas))
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("VENTAS ANULADAS", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("FECHA INICIO");

        jLabel5.setText("FECHA FINAL");

        cmbDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOLETA", "FACTURA" }));

        btnBuscarVentasDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/drive_magnify.png"))); // NOI18N
        btnBuscarVentasDocumentos.setText("BUSCAR");
        btnBuscarVentasDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVentasDocumentosActionPerformed(evt);
            }
        });

        btnImprimirVentasDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/impresora1.png"))); // NOI18N
        btnImprimirVentasDocumentos.setText("IMPRIMIR");
        btnImprimirVentasDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirVentasDocumentosActionPerformed(evt);
            }
        });

        jLabel2.setText("DINERO RECAUDADO");

        txtDineroRecaudadoDocumento.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcFechaInicioVentasDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcFechaFinalVentasDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(cmbDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarVentasDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnImprimirVentasDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDineroRecaudadoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcFechaFinalVentasDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcFechaInicioVentasDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarVentasDocumentos)
                        .addComponent(btnImprimirVentasDocumentos)
                        .addComponent(jLabel2)
                        .addComponent(txtDineroRecaudadoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("VENTAS X DOCUMENTOS", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("FECHA INICIO");

        jLabel7.setText("FECHA FINAL");

        btnBuscarVentasContado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/drive_magnify.png"))); // NOI18N
        btnBuscarVentasContado.setText("BUSCAR");
        btnBuscarVentasContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVentasContadoActionPerformed(evt);
            }
        });

        jLabel9.setText("DINERO RECAUDADO");

        txtDineroRecadadoVentasContado.setEnabled(false);

        btnIMprimirVentasContado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/impresora1.png"))); // NOI18N
        btnIMprimirVentasContado.setText("IMPRIMIR");
        btnIMprimirVentasContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIMprimirVentasContadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(dcFechaInicioVentasContado, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dcFechaFinalVentasContado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnBuscarVentasContado, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(btnIMprimirVentasContado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(txtDineroRecadadoVentasContado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcFechaFinalVentasContado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcFechaInicioVentasContado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscarVentasContado)
                        .addComponent(btnIMprimirVentasContado)
                        .addComponent(txtDineroRecadadoVentasContado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("VENTAS AL CONTADO", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("CLIENTE");

        txtCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClienteFocusLost(evt);
            }
        });
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(613, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("VENTAS X CLIENTE", jPanel4);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("DETALLE DE LA VENTA...");

        tabla_reporte_detalle_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_reporte_detalle_ventas);

        txtCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cross.png"))); // NOI18N
        txtCerrar.setText("CERRAR");
        txtCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txtCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane5)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_reporte_ventasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_reporte_ventasMousePressed
        // TODO add your handling code here:
        int fila = tabla_reporte_ventas.getSelectedRow();
        DetalleVentaBD oDetalleCompraBD = new DetalleVentaBD();
        int idcompra = Integer.parseInt(tabla_temporal_ventas.getValueAt(fila, 0).toString());

        tabla_temporal_detalle_ventas = oDetalleCompraBD.buscarDetalleVenta(idcompra);
        tabla_reporte_detalle_ventas.setModel(tabla_temporal_detalle_ventas);

        AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_detalle_ventas);

        ColorearColumnasJTable co15 = new ColorearColumnasJTable(1, Color.YELLOW);
        ColorearColumnasJTable co17 = new ColorearColumnasJTable(5, Color.PINK);

        tabla_reporte_ventas.getColumnModel().getColumn(1).setCellRenderer(co15);
        tabla_reporte_ventas.getColumnModel().getColumn(5).setCellRenderer(co17);
    }//GEN-LAST:event_tabla_reporte_ventasMousePressed

    private void txtCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_txtCerrarActionPerformed

    private void btnIMprimirVentasContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIMprimirVentasContadoActionPerformed
        // TODO add your handling code here:

        try {
            Conexion mysql = new Conexion();
            Connection cn = mysql.conectar();

            if (dcFechaInicioVentasContado.getDate() != null) {
                if (dcFechaFinalVentasContado.getDate() != null) {
                    JasperReport reporte = null;
                    InputStream reportStream;

                    String ruta = "/CapaPresentacion/Reportes/Reporte_Ventas_TipoPago.jasper";

                    Map parametro = new HashMap();
                    parametro.clear();
                    parametro.put("fechaInicio", dcn.format(dcFechaInicioVentasContado.getDate()));
                    parametro.put("fechaFinal", dcn.format(dcFechaFinalVentasContado.getDate()));
                    parametro.put("tienda", Login_IU.tienda);

                    reportStream = ReporteVentasVarios_IU.class.getResourceAsStream(ruta);
                    reporte = (JasperReport) JRLoader.loadObject(reportStream);

                    JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);
                    JasperViewer jvmostrar = new JasperViewer(jprint, false);

                    jvmostrar.setTitle("REPORTE DE VENTAS - CONTADO");
                    jvmostrar.setVisible(true);
                    jvmostrar.setExtendedState(6);
                    jvmostrar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

                } else {
                    advertencia("Regresa a la fecha de inicio");
                }
            } else {
                advertencia("Regresa a la fecha del final");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnIMprimirVentasContadoActionPerformed

    private void btnBuscarVentasContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVentasContadoActionPerformed
        // TODO add your handling code here:
        try {
            limpiar_tabla_formulario();
            VentaBD oVentaBD = new VentaBD();
            if (dcFechaInicioVentasContado.getDate() != null) {
                if (dcFechaFinalVentasContado.getDate() != null) {
                    String fechaInicio = dcn.format(dcFechaInicioVentasContado.getDate());
                    String fechaFinal = dcn.format(dcFechaFinalVentasContado.getDate());
                    String tienda = Login_IU.tienda;
                    tabla_temporal = oVentaBD.reportarVentaVarios(fechaInicio, fechaFinal, "CONTADO", "ATENDIDO", tienda);
                    int cant = tabla_temporal.getRowCount();
                    for (int i = 0; i < cant; i++) {
                        String idventa = tabla_temporal.getValueAt(i, 0).toString();
                        String cliente = tabla_temporal.getValueAt(i, 15).toString();
                        String documento = tabla_temporal.getValueAt(i, 3).toString();
                        String correlativo = tabla_temporal.getValueAt(i, 4).toString();
                        String totalPagar = tabla_temporal.getValueAt(i, 11).toString();
                        String fecha = tabla_temporal.getValueAt(i, 1).toString();
                        tienda = tabla_temporal.getValueAt(i, 17).toString();;
                        String estado = tabla_temporal.getValueAt(i, 7).toString();;
                        Object[] data = {idventa, cliente, documento, correlativo, totalPagar, fecha, estado};
                        tabla_temporal_ventas.addRow(data);

                        AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_ventas);
                        AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_detalle_ventas);
        ColorearColumnasJTable co15 = new ColorearColumnasJTable(1, Color.YELLOW);
        ColorearColumnasJTable co17 = new ColorearColumnasJTable(5, Color.PINK);

        tabla_reporte_ventas.getColumnModel().getColumn(1).setCellRenderer(co15);
        tabla_reporte_ventas.getColumnModel().getColumn(5).setCellRenderer(co17);
                    }
                    tabla_reporte_ventas.setModel(tabla_temporal_ventas);
                    double total = dineroRecaudado();
                    DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.ENGLISH);
                    DecimalFormat df = new DecimalFormat("#.#", symbols);
                    String df_total = df.format(total);
                    txtDineroRecadadoVentasContado.setText(String.valueOf(df_total));
                    AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_ventas);
                    AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_detalle_ventas);
        ColorearColumnasJTable co15 = new ColorearColumnasJTable(1, Color.YELLOW);
        ColorearColumnasJTable co17 = new ColorearColumnasJTable(5, Color.PINK);

        tabla_reporte_ventas.getColumnModel().getColumn(1).setCellRenderer(co15);
        tabla_reporte_ventas.getColumnModel().getColumn(5).setCellRenderer(co17);
                } else {
                    advertencia("Ingrese la fecha de inicio");
                }
            } else {
                advertencia("Ingrese la fecha de final");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnBuscarVentasContadoActionPerformed

    private void btnImprimirVentasDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirVentasDocumentosActionPerformed
        // TODO add your handling code here:
        try {
            Conexion mysql = new Conexion();
            Connection cn = mysql.conectar();

            if (dcFechaFinalVentasDocumento.getDate() != null) {
                if (dcFechaInicioVentasDocumento.getDate() != null) {
                    JasperReport reporte = null;
                    InputStream reportStream;

                    String ruta = "/CapaPresentacion/Reportes/Reporte_Ventas_Documentos.jasper";

                    Map parametro = new HashMap();
                    parametro.clear();
                    parametro.put("fechaInicio", dcn.format(dcFechaInicioVentasDocumento.getDate()));
                    parametro.put("fechaFinal", dcn.format(dcFechaFinalVentasDocumento.getDate()));
                    parametro.put("documento", (cmbDocumento.getSelectedItem()));
                    parametro.put("tienda", Login_IU.tienda);

                    reportStream = ReporteVentasVarios_IU.class.getResourceAsStream(ruta);
                    reporte = (JasperReport) JRLoader.loadObject(reportStream);

                    JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);
                    JasperViewer jvmostrar = new JasperViewer(jprint, false);

                    jvmostrar.setTitle("REPORTE DE VENTAS - DOCUMENTOS");
                    jvmostrar.setVisible(true);
                    jvmostrar.setExtendedState(6);
                    jvmostrar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

                } else {
                    advertencia("Regresa a la fecha de inicio");
                }
            } else {
                advertencia("Regresa a la fecha del final");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnImprimirVentasDocumentosActionPerformed

    private void btnBuscarVentasDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVentasDocumentosActionPerformed
        // TODO add your handling code here:
        try {
            limpiar_tabla_formulario();
            VentaBD oVentaBD = new VentaBD();
            if (dcFechaFinalVentasDocumento.getDate() != null) {
                if (dcFechaInicioVentasDocumento.getDate() != null) {
                    String fechaInicio = dcn.format(dcFechaInicioVentasDocumento.getDate());
                    String fechaFinal = dcn.format(dcFechaFinalVentasDocumento.getDate());
                    String documento = cmbDocumento.getSelectedItem().toString();
                    String tienda = Login_IU.tienda;
                    tabla_temporal = oVentaBD.reportarVentaDocumentos(fechaInicio, fechaFinal, documento, "ATENDIDO", tienda);
                    int cant = tabla_temporal.getRowCount();
                    for (int i = 0; i < cant; i++) {
                        String idventa = tabla_temporal.getValueAt(i, 0).toString();
                        String cliente = tabla_temporal.getValueAt(i, 15).toString();
                        String documentoo = tabla_temporal.getValueAt(i, 3).toString();
                        String correlativo = tabla_temporal.getValueAt(i, 4).toString();
                        String totalPagar = tabla_temporal.getValueAt(i, 11).toString();
                        String fecha = tabla_temporal.getValueAt(i, 1).toString();
                        tienda = tabla_temporal.getValueAt(i, 17).toString();
                        String estado = tabla_temporal.getValueAt(i, 7).toString();
                        Object[] data = {idventa, cliente, documentoo, correlativo, totalPagar, fecha, estado};
                        tabla_temporal_ventas.addRow(data);
                        AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_ventas);
                        AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_detalle_ventas);
        ColorearColumnasJTable co15 = new ColorearColumnasJTable(1, Color.YELLOW);
        ColorearColumnasJTable co17 = new ColorearColumnasJTable(5, Color.PINK);

        tabla_reporte_ventas.getColumnModel().getColumn(1).setCellRenderer(co15);
        tabla_reporte_ventas.getColumnModel().getColumn(5).setCellRenderer(co17);
                    }
                    tabla_reporte_ventas.setModel(tabla_temporal_ventas);
                    double total = dineroRecaudado();
                    DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.ENGLISH);
                    DecimalFormat df = new DecimalFormat("#.#", symbols);
                    String df_total = df.format(total);
                    txtDineroRecaudadoDocumento.setText("" + df_total);
                    AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_ventas);
                    AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_detalle_ventas);
        ColorearColumnasJTable co15 = new ColorearColumnasJTable(1, Color.YELLOW);
        ColorearColumnasJTable co17 = new ColorearColumnasJTable(5, Color.PINK);

        tabla_reporte_ventas.getColumnModel().getColumn(1).setCellRenderer(co15);
        tabla_reporte_ventas.getColumnModel().getColumn(5).setCellRenderer(co17);
                } else {
                    advertencia("Ingrese la fecha de inicio");
                }
            } else {
                advertencia("Ingrese la fecha de final");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnBuscarVentasDocumentosActionPerformed

    private void btnImprimirVentasAnuladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirVentasAnuladasActionPerformed
        // TODO add your handling code here:
        try {
            Conexion mysql = new Conexion();
            Connection cn = mysql.conectar();

            if (dcFechaInicioVentasAnuladas.getDate() != null) {
                if (dcFechaFinalVentasAnuladas.getDate() != null) {
                    JasperReport reporte = null;
                    InputStream reportStream;

                    String ruta = "/CapaPresentacion/Reportes/Reportes_Ventas_Anuladas.jasper";

                    Map parametro = new HashMap();
                    parametro.clear();
                    parametro.put("fechaInicio", dcn.format(dcFechaInicioVentasAnuladas.getDate()));
                    parametro.put("fechaFinal", dcn.format(dcFechaFinalVentasAnuladas.getDate()));
                    parametro.put("tienda", Login_IU.tienda);

                    reportStream = ReporteComprasVarios_IU.class.getResourceAsStream(ruta);
                    reporte = (JasperReport) JRLoader.loadObject(reportStream);

                    JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);
                    JasperViewer jvmostrar = new JasperViewer(jprint, false);

                    jvmostrar.setTitle("REPORTE DE VENTAS ANULADAS");
                    jvmostrar.setVisible(true);
                    jvmostrar.setExtendedState(6);
                    jvmostrar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

                } else {
                    advertencia("Regresa a la fecha de inicio");
                }
            } else {
                advertencia("Regresa a la fecha del final");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnImprimirVentasAnuladasActionPerformed

    private void btnBuscarventasAnuladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarventasAnuladasActionPerformed
        // TODO add your handling code here:
        try {
            limpiar_tabla_formulario();
            VentaBD oVentaBD = new VentaBD();
            if (dcFechaFinalVentasAnuladas.getDate() != null) {
                if (dcFechaInicioVentasAnuladas.getDate() != null) {
                    String fechaInicio = dcn.format(dcFechaInicioVentasAnuladas.getDate());
                    String fechaFinal = dcn.format(dcFechaFinalVentasAnuladas.getDate());
                    String tienda = Login_IU.tienda;
                    tabla_temporal = oVentaBD.reportarVentaVarios(fechaInicio, fechaFinal, "CONTADO", "ANULADO", tienda);
                    int cant = tabla_temporal.getRowCount();
                    for (int i = 0; i < cant; i++) {
                        String idventa = tabla_temporal.getValueAt(i, 0).toString();
                        String cliente = tabla_temporal.getValueAt(i, 15).toString();
                        String documento = tabla_temporal.getValueAt(i, 3).toString();
                        String correlativo = tabla_temporal.getValueAt(i, 4).toString();
                        String totalPagar = tabla_temporal.getValueAt(i, 11).toString();
                        String fecha = tabla_temporal.getValueAt(i, 1).toString();
                        String hora = tabla_temporal.getValueAt(i, 2).toString();
                        String pagoCon = tabla_temporal.getValueAt(i, 12).toString();
                        String vuelto = tabla_temporal.getValueAt(i, 13).toString();
                        String formaPago = tabla_temporal.getValueAt(i, 6).toString();
                        String moneda = tabla_temporal.getValueAt(i, 8).toString();
                        String uDni = tabla_temporal.getValueAt(i, 16).toString();
                        tienda = tabla_temporal.getValueAt(i, 17).toString();
                        String estado = tabla_temporal.getValueAt(i, 7).toString();
                        Object[] data = {idventa, cliente, documento, correlativo, totalPagar, fecha, estado};
                        tabla_temporal_ventas.addRow(data);

                        AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_ventas);
                        AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_detalle_ventas);
        ColorearColumnasJTable co15 = new ColorearColumnasJTable(1, Color.YELLOW);
        ColorearColumnasJTable co17 = new ColorearColumnasJTable(5, Color.PINK);

        tabla_reporte_ventas.getColumnModel().getColumn(1).setCellRenderer(co15);
        tabla_reporte_ventas.getColumnModel().getColumn(5).setCellRenderer(co17);
                    }
                    tabla_reporte_ventas.setModel(tabla_temporal_ventas);
                    AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_ventas);
                    AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_detalle_ventas);
        ColorearColumnasJTable co15 = new ColorearColumnasJTable(1, Color.YELLOW);
        ColorearColumnasJTable co17 = new ColorearColumnasJTable(5, Color.PINK);

        tabla_reporte_ventas.getColumnModel().getColumn(1).setCellRenderer(co15);
        tabla_reporte_ventas.getColumnModel().getColumn(5).setCellRenderer(co17);
                } else {
                    advertencia("Ingrese la fecha de inicio");
                }
            } else {
                advertencia("Ingrese la fecha de final");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnBuscarventasAnuladasActionPerformed

    private void txtClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyReleased
        // TODO add your handling code here:
        try {
            limpiar_tabla_formulario();
            VentaBD oVentaBD = new VentaBD();
            String cliente = txtCliente.getText();
            String tienda = Login_IU.tienda;
            tabla_temporal = oVentaBD.reportarVentaCliente(cliente, tienda);
            int cant = tabla_temporal.getRowCount();
            for (int i = 0; i < cant; i++) {
                String idventa = tabla_temporal.getValueAt(i, 0).toString();
                cliente = tabla_temporal.getValueAt(i, 15).toString();
                String documento = tabla_temporal.getValueAt(i, 3).toString();
                String correlativo = tabla_temporal.getValueAt(i, 4).toString();
                String totalPagar = tabla_temporal.getValueAt(i, 11).toString();
                String fecha = tabla_temporal.getValueAt(i, 1).toString();
                String estado = tabla_temporal.getValueAt(i, 7).toString();
                Object[] data = {idventa, cliente, documento, correlativo, totalPagar, fecha, estado};
                tabla_temporal_ventas.addRow(data);

                AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_ventas);
                AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_detalle_ventas);
            }
            tabla_reporte_ventas.setModel(tabla_temporal_ventas);
            double total = dineroRecaudado();
            DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.ENGLISH);
            DecimalFormat df = new DecimalFormat("#.#", symbols);
            String df_total = df.format(total);
            txtDineroRecaudadoDocumento.setText("" + df_total);
            AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_ventas);
            AjustarColumnasJTable.ajustarAnchoColumnas(tabla_reporte_detalle_ventas);
        ColorearColumnasJTable co15 = new ColorearColumnasJTable(1, Color.YELLOW);
        ColorearColumnasJTable co17 = new ColorearColumnasJTable(5, Color.PINK);

        tabla_reporte_ventas.getColumnModel().getColumn(1).setCellRenderer(co15);
        tabla_reporte_ventas.getColumnModel().getColumn(5).setCellRenderer(co17);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtClienteKeyReleased

    private void txtClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteFocusGained
        // TODO add your handling code here:
        txtCliente.setBackground(Color.yellow);
    }//GEN-LAST:event_txtClienteFocusGained

    private void txtClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteFocusLost
        // TODO add your handling code here:

        txtCliente.setBackground(Color.white);
    }//GEN-LAST:event_txtClienteFocusLost

    private void txtClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtClienteKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarVentasContado;
    private javax.swing.JButton btnBuscarVentasDocumentos;
    private javax.swing.JButton btnBuscarventasAnuladas;
    private javax.swing.JButton btnIMprimirVentasContado;
    private javax.swing.JButton btnImprimirVentasAnuladas;
    private javax.swing.JButton btnImprimirVentasDocumentos;
    private javax.swing.JComboBox<String> cmbDocumento;
    private com.toedter.calendar.JDateChooser dcFechaFinalVentasAnuladas;
    private com.toedter.calendar.JDateChooser dcFechaFinalVentasContado;
    private com.toedter.calendar.JDateChooser dcFechaFinalVentasDocumento;
    private com.toedter.calendar.JDateChooser dcFechaInicioVentasAnuladas;
    private com.toedter.calendar.JDateChooser dcFechaInicioVentasContado;
    private com.toedter.calendar.JDateChooser dcFechaInicioVentasDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable tabla_reporte_detalle_ventas;
    private javax.swing.JTable tabla_reporte_ventas;
    private javax.swing.JButton txtCerrar;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDineroRecadadoVentasContado;
    private javax.swing.JTextField txtDineroRecaudadoDocumento;
    // End of variables declaration//GEN-END:variables
}
